"""MIS-CTU locker database

Revision ID: d568c9d94c8d
Revises: 
Create Date: 2020-05-29 09:25:33.413557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd568c9d94c8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('mssv', sa.String(length=8), nullable=True),
    sa.Column('rfid', sa.String(length=10), nullable=True),
    sa.Column('fing', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_fing'), 'user', ['fing'], unique=True)
    op.create_index(op.f('ix_user_mssv'), 'user', ['mssv'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_rfid'), 'user', ['rfid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_rfid'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_mssv'), table_name='user')
    op.drop_index(op.f('ix_user_fing'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
